version: '3.3'
services:
   mongo:
     image: mongo:4.2.5
     ports:
       - "27017:27017"
   app:
     build:
       context: ""
       dockerfile: Dockerfile
     environment:
       WAIT_HOSTS: mongo:27017
     depends_on:
       - "mongo"
     ports:
       - '8080:8080'

